require("v9.plugin_config.colorscheme")
require("v9.plugin_config.lualine")
require("v9.plugin_config.nvim-tree")
require("v9.plugin_config.telescope")
require("v9.plugin_config.treesitter")
require("v9.plugin_config.lsp")
require("v9.plugin_config.completions")
require("v9.plugin_config.toggleterm")
require("v9.plugin_config.alpha")
require("v9.plugin_config.lichess")
-- require('v9.plugin_config.zone')
require("v9.plugin_config.autopairs")
require("v9.plugin_config.comment-nvim")
require("v9.plugin_config.noice")
require("v9.plugin_config.harpoon")
-- require('v9.plugin_config.peek')
require("v9.plugin_config.blackjack")
require("v9.plugin_config.leap")
require("v9.plugin_config.vim-be-good")
require("v9.plugin_config.lab")
require("v9.plugin_config.indent")
require("v9.plugin_config.themery")
require("v9.plugin_config.vim-illuminate")
-- require('v9.plugin_config.null')
require("v9.plugin_config.gitsigns")
